import type { Metadata } from "next";
import { pixelFont1} from "@/components/ui/fonts";
import SideNav from "./SideNav";
import "./globals.css";

export const metadata: Metadata = {
  title: "Ejercicios UTN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={`${pixelFont1.variable} antialiased`}>
      <body className="min-h-screen flex flex-col">
        <SideNav />
        {children}
      </body>
    </html>
  );
}
