import type { Metadata } from "next";
import { inter, spaceGrotesk } from "../components/ui/fonts";
import SideNav from "./SideNav";
import "./globals.css";

export const metadata: Metadata = {
  title: "Ejercicios UTN",
  description: "Generated by create next app",
  viewport: {
    width: "device-width",
    initialScale: 1,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={`${inter.variable} ${spaceGrotesk.variable} antialiased`}>
      <body className="min-h-screen flex flex-col">
        <SideNav />
        {children}
      </body>
    </html>
  );
}
