import type { Metadata } from "next";
import { inter, spaceGrotesk } from "./ui/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Ejercicios UTN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={`${inter.variable} ${spaceGrotesk.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
